name: cleanarchitecture
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # Service locator
  get_it: ^4.0.1
  # MobX for state management
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  mobx_codegen: ^1.0.3
  
flutter:

  uses-material-design: true

